
services:
  backender:
    build:
      context: .
      dockerfile: ./backer/godotask/Dockerfile
    stdin_open: true
    tty: true
    command: go run ./cmd/boot/main.go
    volumes:
      - ./backer/godotask:/usr/local/go/godotask
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - beta-app-network

  fronter:
    build:
      context: ./fronter
      dockerfile: Dockerfile
    depends_on:
      - backender
    networks:
      - beta-app-network

  betanginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fronter
      - backender
    networks:
      - beta-app-network
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dbgodotask
      POSTGRES_PASSWORD: dbgodotask
      POSTGRES_DB: dbgodotask
      POSTGRES_TEST_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - beta-app-network

networks:
  beta-app-network:
    name: beta-app-network
    driver: bridge