version: '3'

services:
  godotask:
    container_name: godotask
    build:
      context: .
      dockerfile: godotask/DockerFile.compose
    stdin_open: true
    tty: true
    command: bash -c "/bin/bash"
    volumes:
      - ./godotask:/usr/local/go/godotask
    ports:
      - 8080:8080
    depends_on:
      - "dbgodotask"

  dbgodotask:
    container_name: dbgodotask
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbgodotask
      POSTGRES_USER: dbgodotask
      POSTGRES_PASSWORD: dbgodotask
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local