package model

func Models() []interface{} {
	return []interface{}{
		&User{},
		&Assessment{},
		&Task{},
		&Memory{},
		&MemoryContext{},
		&TechnicalFactor{},
		&KnowledgeTransformation{},
		&Book{},
		&HeuristicsAnalysis{},
		&HeuristicsTracking{},
		&HeuristicsInsight{},
		&HeuristicsPattern{},
		&HeuristicsModel{},
		&RobotSpecification{},
		&OptimizationModel{},
		&PhenomenologicalFramework{},
		&KnowledgePattern{},
		&ProcessOptimization{},
		&TeachingFreeControl{},
		&LanguageOptimization{},
		&StateEvaluation{},
		&ToolMatchingResult{},
		&ProcessMonitoring{},
		&LearningPattern{},
		&QuantificationLabel{},
		&ImageAnnotation{},
		&LabelRevision{},
		&LabelDataset{},
		&LabelRelation{},
		&VisualMetaphor{},
		&UserCalibration{},
		&MultimodalData{},
	}
}
