package seed

import (
	"log"
	"time"

	"github.com/godotask/model"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

// SeedQuantificationLabels - 定量化ラベルのシードデータ
func SeedQuantificationLabels(db *gorm.DB) error {
	log.Println("Starting quantification labels seeding...")

	labels := []model.QuantificationLabel{
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 1,
			OriginalText:    "高精度加工",
			NormalizedText:  "high precision machining",
			Category:        "manufacturing_quality",
			Context:         "machining_operations",
			Domain:          "manufacturing",
			Value:           0.95,
			Unit:            "accuracy_ratio",
			MinRange:        0.90,
			MaxRange:        1.00,
			TypicalValue:    0.95,
			Precision:       3,
			Confidence:      0.90,
			AbstractLevel:   "concrete",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"精密加工", "品質管理", "寸法精度", "表面粗さ"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"precision", "quality", "manufacturing", "accuracy"},
			}),
			Accuracy:        0.92,
			Consistency:     0.88,
			Reproducibility: 0.85,
			Usability:       0.95,
			Source:          "expert_knowledge",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 1,
			OriginalText:    "切削条件最適化",
			NormalizedText:  "cutting condition optimization",
			Category:        "process_optimization",
			Context:         "machining_parameters",
			Domain:          "manufacturing",
			Value:           0.85,
			Unit:            "efficiency_ratio",
			MinRange:        0.70,
			MaxRange:        1.00,
			TypicalValue:    0.85,
			Precision:       2,
			Confidence:      0.88,
			AbstractLevel:   "operational",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"切削速度", "送り", "切込み量", "工具寿命"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"optimization", "cutting", "parameters", "efficiency"},
			}),
			Accuracy:        0.85,
			Consistency:     0.82,
			Reproducibility: 0.80,
			Usability:       0.90,
			Source:          "field_data",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 2,
			OriginalText:    "ロボット協働作業",
			NormalizedText:  "robot collaborative work",
			Category:        "human_robot_collaboration",
			Context:         "manufacturing_automation",
			Domain:          "robotics",
			Value:           0.78,
			Unit:            "collaboration_index",
			MinRange:        0.50,
			MaxRange:        1.00,
			TypicalValue:    0.78,
			Precision:       2,
			Confidence:      0.85,
			AbstractLevel:   "systemic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"安全性", "効率性", "柔軟性", "学習能力"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"collaboration", "robotics", "automation", "safety"},
			}),
			Accuracy:        0.88,
			Consistency:     0.85,
			Reproducibility: 0.82,
			Usability:       0.92,
			Source:          "research_data",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 3,
			OriginalText:    "品質検査自動化",
			NormalizedText:  "quality inspection automation",
			Category:        "quality_assurance",
			Context:         "inspection_systems",
			Domain:          "quality_control",
			Value:           0.92,
			Unit:            "detection_rate",
			MinRange:        0.85,
			MaxRange:        1.00,
			TypicalValue:    0.92,
			Precision:       3,
			Confidence:      0.95,
			AbstractLevel:   "operational",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"画像処理", "機械学習", "欠陥検出", "統計的品質管理"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"inspection", "automation", "quality", "detection"},
			}),
			Accuracy:        0.94,
			Consistency:     0.91,
			Reproducibility: 0.89,
			Usability:       0.96,
			Source:          "production_data",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 3,
			OriginalText:    "エネルギー効率最適化",
			NormalizedText:  "energy efficiency optimization",
			Category:        "energy_management",
			Context:         "sustainable_manufacturing",
			Domain:          "sustainability",
			Value:           0.75,
			Unit:            "energy_reduction_ratio",
			MinRange:        0.60,
			MaxRange:        0.90,
			TypicalValue:    0.75,
			Precision:       2,
			Confidence:      0.82,
			AbstractLevel:   "strategic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"省エネルギー", "CO2削減", "コスト最適化", "持続可能性"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"energy", "efficiency", "sustainability", "optimization"},
			}),
			Accuracy:        0.80,
			Consistency:     0.78,
			Reproducibility: 0.75,
			Usability:       0.85,
			Source:          "environmental_data",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 4,
			OriginalText:    "技能伝承システム",
			NormalizedText:  "skill transfer system",
			Category:        "knowledge_management",
			Context:         "workforce_development",
			Domain:          "human_resources",
			Value:           0.68,
			Unit:            "transfer_effectiveness",
			MinRange:        0.50,
			MaxRange:        0.90,
			TypicalValue:    0.68,
			Precision:       2,
			Confidence:      0.75,
			AbstractLevel:   "systemic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"暗黙知", "形式知", "OJT", "デジタル化"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"skill", "knowledge", "transfer", "training"},
			}),
			Accuracy:        0.72,
			Consistency:     0.70,
			Reproducibility: 0.68,
			Usability:       0.80,
			Source:          "training_data",
			Validated:       false,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 5,
			OriginalText:    "プロセス監視・制御",
			NormalizedText:  "process monitoring control",
			Category:        "process_control",
			Context:         "real_time_monitoring",
			Domain:          "automation",
			Value:           0.89,
			Unit:            "monitoring_coverage",
			MinRange:        0.80,
			MaxRange:        1.00,
			TypicalValue:    0.89,
			Precision:       2,
			Confidence:      0.92,
			AbstractLevel:   "operational",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"IoT", "センサー", "データ分析", "異常検知"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"monitoring", "control", "sensors", "iot"},
			}),
			Accuracy:        0.91,
			Consistency:     0.88,
			Reproducibility: 0.86,
			Usability:       0.93,
			Source:          "sensor_data",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 6,
			OriginalText:    "AI駆動最適化",
			NormalizedText:  "ai driven optimization",
			Category:        "artificial_intelligence",
			Context:         "intelligent_manufacturing",
			Domain:          "ai_ml",
			Value:           0.82,
			Unit:            "optimization_improvement",
			MinRange:        0.70,
			MaxRange:        0.95,
			TypicalValue:    0.82,
			Precision:       2,
			Confidence:      0.87,
			AbstractLevel:   "strategic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"機械学習", "深層学習", "予測分析", "自動最適化"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"ai", "machine_learning", "optimization", "prediction"},
			}),
			Accuracy:        0.85,
			Consistency:     0.83,
			Reproducibility: 0.81,
			Usability:       0.88,
			Source:          "ai_models",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 7,
			OriginalText:    "デジタルツイン",
			NormalizedText:  "digital twin",
			Category:        "digital_transformation",
			Context:         "virtual_manufacturing",
			Domain:          "digitalization",
			Value:           0.73,
			Unit:            "simulation_accuracy",
			MinRange:        0.60,
			MaxRange:        0.90,
			TypicalValue:    0.73,
			Precision:       2,
			Confidence:      0.80,
			AbstractLevel:   "systemic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"仮想現実", "シミュレーション", "予測保全", "デジタル化"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"digital_twin", "simulation", "virtual", "prediction"},
			}),
			Accuracy:        0.78,
			Consistency:     0.75,
			Reproducibility: 0.72,
			Usability:       0.82,
			Source:          "simulation_data",
			Validated:       false,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 8,
			OriginalText:    "予知保全システム",
			NormalizedText:  "predictive maintenance system",
			Category:        "maintenance_management",
			Context:         "equipment_reliability",
			Domain:          "maintenance",
			Value:           0.86,
			Unit:            "failure_prediction_rate",
			MinRange:        0.75,
			MaxRange:        0.95,
			TypicalValue:    0.86,
			Precision:       2,
			Confidence:      0.90,
			AbstractLevel:   "operational",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"振動解析", "温度監視", "摩耗予測", "故障診断"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"predictive", "maintenance", "reliability", "diagnosis"},
			}),
			Accuracy:        0.88,
			Consistency:     0.85,
			Reproducibility: 0.83,
			Usability:       0.91,
			Source:          "maintenance_records",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 9,
			OriginalText:    "セーフティ機能統合",
			NormalizedText:  "safety function integration",
			Category:        "safety_systems",
			Context:         "industrial_safety",
			Domain:          "safety",
			Value:           0.94,
			Unit:            "safety_compliance_rate",
			MinRange:        0.90,
			MaxRange:        1.00,
			TypicalValue:    0.94,
			Precision:       3,
			Confidence:      0.98,
			AbstractLevel:   "regulatory",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"リスクアセスメント", "安全規格", "緊急停止", "保護装置"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"safety", "compliance", "protection", "emergency"},
			}),
			Accuracy:        0.96,
			Consistency:     0.94,
			Reproducibility: 0.92,
			Usability:       0.98,
			Source:          "safety_standards",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.New().String(),
			UserID:       	 1,
			TaskID:       	 10,
			OriginalText:    "生産性向上指標",
			NormalizedText:  "productivity improvement index",
			Category:        "performance_metrics",
			Context:         "manufacturing_kpi",
			Domain:          "performance",
			Value:           0.79,
			Unit:            "productivity_gain",
			MinRange:        0.60,
			MaxRange:        1.20,
			TypicalValue:    0.79,
			Precision:       2,
			Confidence:      0.83,
			AbstractLevel:   "strategic",
			RelatedConcepts: model.JSON(map[string]interface{}{
				"concepts": []string{"OEE", "稼働率", "品質率", "パフォーマンス"},
			}),
			SemanticTags: model.JSON(map[string]interface{}{
				"tags": []string{"productivity", "performance", "efficiency", "metrics"},
			}),
			Accuracy:        0.81,
			Consistency:     0.79,
			Reproducibility: 0.77,
			Usability:       0.85,
			Source:          "production_metrics",
			Validated:       true,
			Version:         1,
			CreatedBy:       "system",
			UpdatedBy:       "system",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
	}

	// Insert data
	for _, label := range labels {
		if err := db.Create(&label).Error; err != nil {
			log.Printf("Error inserting quantification label %s: %v", label.ID, err)
			return err
		}
	}

	log.Printf("✓ Successfully seeded %d quantification labels", len(labels))
	return nil
}