FROM golang:1.21

RUN mkdir -p /usr/local/go/godotask
WORKDIR /usr/local/go/godotask

COPY backer/godotask/go.mod .
COPY backer/godotask/go.sum .

RUN go mod download

# アプリケーションコードをコピー
COPY backer/godotask/ .
